engines:
  fixme:
    enabled: true
  phpcodesniffer:
    enabled: true
  phpmd:
    enabled: true
ratings:
   paths:
   - "Schnittstabil/**/*"
   - "**.php"
   - "**.module"
   - "**.inc"
exclude_paths:
- "tests/**/*"
- ".codeclimate.yml"
- "sami_configuration.php"
